# Config for Air (hot reload)
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/devapi.exe ."
bin = "./tmp/devapi.exe"                # Binary yang akan dijalankan
  full_bin = ".\\tmp\\devapi.exe"        # Full path binary 
  include_ext = ["go", "env", "yaml", "yml"]    # Extensi file yang di-monitor
  exclude_dir = [
    "vendor",
    "tmp",
    "docs",
    "static",
    "node_modules",
    ".git"
  ]
  delay = 800                             # Lebih responsif
  stop_on_error = true                    # Berhenti jika build error
  kill_signal = "CTRL+C"a
  kill_delay = "500ms"                    # Waktu tunggu sebelum kill process lama

[log]
  time = true
  main_only = false                       # Tampilkan semua log
  prefix = "[DEVAPI]"                     # Identifikasi log project

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  app = "blue"